server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/farmers-market-db
    username: admin
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret: 'secretKey'
    expirationMs: 86400000
