version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: farmers-market-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5433